### ISSUE TITLE
Right click menu shows up in the wrong spot

### ISSUE THREAD

**Issue by encody** [simgunz/anki21-addons_minimize-to-tray#1]
Thanks for the addon, so far so good.

I'm on Windows 10, and when I right-click on the icon, this is what appears:

![image](https://user-images.githubusercontent.com/7459638/45938364-de431680-bf8e-11e8-8659-830d51eec892.png)

The right-click menu is misplaced: instead of appearing right next to the mouse, it appears in the lower-right corner of the screen.

Anki installation:
Version 2.1.4
Qt 5.9.2 PyQt 5.9

**Comment by simgunz** [comment]
Thanks for reporting the bug. I think this is likely related to Qt on Windows. I'll have a look soon though.

**Comment by simgunz** [comment]
I have investigated this issue further and using the test script below the menu is displayed in the correct position. So the issue seems related to my implementation or to how anki manages the add on.

```
import sys

from PyQt5.QtGui import QIcon, QPixmap  
from PyQt5.QtWidgets import QApplication, QMenu, QSystemTrayIcon, QDialog

class App:
  def __init__(self):
    # Create a Qt application
    self.app = QApplication(sys.argv)
    
    icon = QIcon("C:\sharedLinux\home.png")
    menu = QMenu()
    settingAction = menu.addAction("setting")
    settingAction.triggered.connect(self.setting)
    exitAction = menu.addAction("exit")
    exitAction.triggered.connect(sys.exit)
    
    self.tray = QSystemTrayIcon()
    self.tray.setIcon(icon)
    self.tray.setContextMenu(menu)
    self.tray.show()
    self.tray.setToolTip("unko!")
    
  def run(self):
    # Enter Qt application main loop
    self.app.exec_()
    sys.exit()

  def setting(self):
    self.dialog = QDialog()
    self.dialog.setWindowTitle("Setting Dialog")
    self.dialog.show()

if __name__ == "__main__":
  app = App()
  app.run()
```

**Comment by simgunz** [comment]
I have tried to ask on the QtForum:
https://forum.qt.io/topic/96026/qmenu-in-qsytemtrayicon-misplaced-in-windows-10

**Comment by simgunz** [comment]
Does this issue still happen?
