### ISSUE TITLE
Startup Failed

### ISSUE THREAD

**Issue by serifold** [simgunz/anki21-addons_minimize-to-tray#11]
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-11-02 10:26:46

When loading Minimize to tray:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "D:\Scoop\persist\anki\data\addons21\85158043\__init__.py", line 12, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by simgunz** [comment]
Can you test again with the latest update (version 2.0.0 of the addon)?

**Comment by serifold** [comment]
> Can you test again with the latest update (version 2.0.0 of the addon)?

Thank you very much, it works!
