### ISSUE TITLE
Not working with Anki 23.10

### ISSUE THREAD

**Issue by mcthesw** [simgunz/anki21-addons_minimize-to-tray#13]
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-12 10:22:21

When loading Minimize to tray:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\user_name\scoop\persist\anki\data\addons21\85158043\__init__.py", line 12, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by simgunz** [comment]
Can you test again with the latest update (version 2.0.0 of the addon)?

**Comment by mcthesw** [comment]
It's OK now, thank you!
