### ISSUE TITLE
new version dose not support Anki ⁨2.1.63

### ISSUE THREAD

**Issue by acp120** [simgunz/anki21-addons_minimize-to-tray#15]
new version dose not support Anki ⁨2.1.63

**Comment by simgunz** [comment]
Hi. Indeed it does not.

Did anki prompt you to update when you opened it?

I did upload the 2.0 version of the addon stating that it only supports 23.10+, so anki should have not proposed the update if you are using 2.1.63.

![Screenshot_20231127_204415](https://github.com/simgunz/anki21-addons_minimize-to-tray/assets/466270/160c938a-26f6-4f42-a3bd-2f49a47a8150)
