### ISSUE TITLE
version 2.0.0 actually dose not support anki-23.10.1-windows-qt6

### ISSUE THREAD

**Issue by Sebastian2333** [simgunz/anki21-addons_minimize-to-tray#16]
An error message will pop up after running Anki in the background for a few minutes.
The debugging information is as follows.

错误
运行出错。请在启动 Anki 时按住 Shift 键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启 Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-26 22:22:28
相关插件：⁨Minimize to tray⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Sebastian\AppData\Roaming\Anki2\addons21\85158043\__init__.py", line 53, in onActivated
    self.showAll()
  File "C:\Users\Sebastian\AppData\Roaming\Anki2\addons21\85158043\__init__.py", line 71, in showAll
    self._showWindows(self.explicitlyHiddenWindows)
  File "C:\Users\Sebastian\AppData\Roaming\Anki2\addons21\85158043\__init__.py", line 88, in _showWindows
    if w.isMinimized() == Qt.WindowState.WindowMinimized:
RuntimeError: wrapped C/C++ object of type CustomLabel has been deleted

<img width="498" alt="image" src="https://github.com/simgunz/anki21-addons_minimize-to-tray/assets/38579551/aaa2c0d3-3d90-46c1-86f9-6168b4c17db8">

Hope to get your timely attention!

**Comment by simgunz** [comment]
Hi, thanks for reporting the issue. Can you try running anki with all other extensions disabled and see if it still happens. This will help me narrow down the possible sources of the issue.

**Comment by Sebastian2333** [comment]
> Hi, thanks for reporting the issue. Can you try running anki with all other extensions disabled and see if it still happens. This will help me narrow down the possible sources of the issue.

When Anki is minimized to the tray and runs in the background for several minutes or hours, this error occurs when clicking the tray icon to run Anki. After several comparison tests, this error will appear regardless of whether this plug-in is used in conjunction with other plug-ins. But when the awesomeTTS plug-in is enabled, this error appears faster and more frequently. Thank you for your attention.
