### ISSUE TITLE
Add-on not available for Anki Version ⁨2.1.65

### ISSUE THREAD

**Issue by inklings42** [simgunz/anki21-addons_minimize-to-tray#17]
Invalid code, or add-on not available for your version of Anki.
Version ⁨2.1.65 (aa9a734f)⁩

Thank you!

**Comment by simgunz** [comment]
Are you using windows? If using linux what distribution version? Qt5 or Qt6? Can you update to the latest anki version 24.06.3?

**Comment by simgunz** [comment]
Closed due to inactivity.
