### ISSUE TITLE
[Feature Request] Add Option to Restart Anki

### ISSUE THREAD

**Issue by zina0316** [simgunz/anki21-addons_minimize-to-tray#19]
Sometimes when I install a add-on, I'll have to manually close, restart Anki
it'll be so nice if there's an option in the tray icon menu to automatically restart

**Comment by simgunz** [comment]
I understand your need regarding Anki, given that installing add-on is common practice, though most applications don’t include a restart button in the tray, as it adds to UI clutter. Users can achieve the same result by manually closing and reopening Anki, so the feature would provide only marginal benefit while deviating from typical user interface practices.
