### ISSUE TITLE
Anki Crash

### ISSUE THREAD

**Issue by yukach** [simgunz/anki21-addons_minimize-to-tray#20]
`
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.2.15-100.fc36.x86_64-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "/home/yk/.local/share/Anki2/addons21/85158043/__init__.py", line 53, in onActivated
    self.showAll()
  File "/home/yk/.local/share/Anki2/addons21/85158043/__init__.py", line 71, in showAll
    self._showWindows(self.explicitlyHiddenWindows)
  File "/home/yk/.local/share/Anki2/addons21/85158043/__init__.py", line 88, in _showWindows
    if w.isMinimized() == Qt.WindowState.WindowMinimized:
RuntimeError: wrapped C/C++ object of type CustomLabel has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-11-07T04:34, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-12-06T04:28, 'None', '']
Google Translate ['1536291224', 2024-12-10T00:39, 'None', mod]
Mini Format Pack ['295889520', 2023-11-02T21:00, 'None', '']
Minimize to tray ['85158043', 2023-11-26T22:18, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1436550454 1536291224 1771074083 2055492159 295889520 85158043

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Button Colours Good Again ['2494384865', 2022-09-27T13:18, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T18:06, 'None', '']
Customize Sidebar ['1988760596', 2020-01-16T00:01, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-12-06T04:35, 'None', mod]
Replay buttons on card ['498789867', 2018-11-18T18:54, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T14:24, 'None', '']
`

**Comment by simgunz** [comment]
I have just released a 2.0.1 version, where I attempted to fix this type of crash. Can you test it?
