### ISSUE TITLE
Since I have updated the minimize-to-tray, I can't use it now.

### ISSUE THREAD

**Issue by Karl-Heinrich-Marx** [simgunz/anki21-addons_minimize-to-tray#6]
# Since I have updated the minimize-to-tray, I can't use it now. The screenshot below is the issue. Thanks!
![image](https://user-images.githubusercontent.com/74743952/145745298-88592d58-8117-41d0-b40e-9e8e85559fae.png)

**Comment by simgunz** [comment]
What version of anki and OS are you using?

**Comment by simgunz** [comment]
Closing due to missing information
